@startuml
skinparam backgroundColor #AAAAAA

rectangle "dependencies" {
  interface "Eq"
  interface "PartialEq"

  rectangle "serde" {
    interface "Serialize"
    interface "Deserialize"
  }

  rectangle "actix_web" {
    interface "FromRequest"
    rectangle "error" {
      struct BlockingError
      interface "ResponseError"
    }
  }

  rectangle "diesel" {
    rectangle "result" {
      struct "Error"
    }
    interface "Selectable"
    interface "Identifiable"
    interface "Queryable"
    interface "Insertable"
    interface "AsChangeset"
  }

  rectangle "chrono" {
    struct "NaiveDateTime"
    struct "DateTime<Utc>"
  }

}

rectangle "applib" {
  interface "From<BlockingError>"
  interface "From<Error>"
  
  struct "Config" {
    database_url: Sring
    port: u16
    jwt_secret: String
    new() -> Self
    database_url(&self: Self): String
    port(&self: Self): u16
    jwt_secret(&self: Self): String
  }

  struct "AppError" {
    status: actix_web::http::StatusCode
    code: String
    message: String
    internal_server_error(): Self
    not_found(): Self
    bad_request(): Self
    use_delete_endpoint_instead(): Self
    invalid_email_password(): Self
    unauthorized(): Self
    user_inactive_or_deleted(): Self
    destination_is_not_reviewed(): Self
  }
  Serialize <|-- AppError
  Debug <|-- AppError
  Display <|-- AppError
  "From<BlockingError>" <|-- AppError
  "ResponseError" <|-- AppError
  "From<Error>" <|-- AppError
}

rectangle "db" {
  rectangle "model" {
    note "All structs implement serde Serilaize and Deserialize" as N1
    note "All structs starting with 'New' implement diesel Insertable" as N2
    note "All structs starting with 'Update' implement diesel AsChangeset" as N3
    note "All other structs implement diesel Identifiable, Queryable, Selectable" as N4
    note "All enums implement Eq, PartialEq, TryFrom<& str>, Into<& str>" as N5

    rectangle "bucketlist-item"{
      struct BucketlistItem {
        id: u64
        destination_id: u64
        owner_id: u64
        start_date: NaiveDateTime
        end_date: NaiveDateTime
        is_favorite: bool
      }
      struct NewBucketlistItem {
        destination_id: u64
        owner_id: u64
        start_date: NaiveDateTime
        end_date: NaiveDateTime
      }
      struct UpdateBucketlistItem {
        start_date: NaiveDateTime
        end_date: NaiveDateTime
      }

      "NaiveDateTime" ---- "BucketlistItem"
      "NaiveDateTime" ---- "NewBucketlistItem"
      "NaiveDateTime" ---- "UpdateBucketlistItem"
    }
    rectangle "destination" {
      struct Destination {
        id: u64
        owner_id: u64
        visiblity: u64
        is_reviewed: bool
        name: String
        latitude: f64
        longitude: f64
      }

      struct NewDestination {
        id: u64
        owner_id: u64
        visiblity: u64
        is_reviewed: bool
        name: String
        latitude: f64
        longitude: f64
      }
      struct UpdateDestination {
        owner_id: Option<u64>
        visiblity: Option<u64>
        is_reviewed: Option<bool>
        name: Option<String>
        latitude: Option<f64>
        longitude: Option<f64>
      }
      enum VisibilityEnum {
        Public
        Private
      }
    }
    
    rectangle "session" {
      struct Session {
        id: u64,
        user_id: u64,
        start_date: NaiveDateTime,
        end_date: NaiveDateTime
      }
      
      struct NewSession {
        user_id: u64,
        start_date: NaiveDateTime,
        end_date: NaiveDateTime
      }
      
      "NaiveDateTime" ---- "Session"
      "NaiveDateTime" ---- "NewSession"
    }

    rectangle "user" {
      struct User {
        id: u64
        role: String
        email: String
        password: String
        status: String
      }
      
      struct NewUser {
        role: String
        email: String
        password: String
      }
      
      struct UpdateUser {
        role: Option<String>
        email: Option<String>
        password: Option<String>
        status: Option<String> 
      }

      enum StatusEnum {
        Active
        Inactive
        Deleted
      }
      
      enum RoleEnum {
        Admin
        Employee
      }
    }
    "FromRequest" <|-- User
  }
  rectangle "predicates" {
    metaclass "destination" {
      available_for_user(user_id: u64): Box<dyn BoxableExpression<destinations::table, Db, SqlType = Bool>> 
    }
  }
  
  rectangle "type Db = Mysql" {
  
  }
  
  rectangle "type DbPool = r2d2::Pool<diesel::r2d2::ConnectionManager<MySqlConnection>>" {
  
  }
  
  rectangle "sql_function! last_inserted_id() -> sql_types::BigInt" {
  }

  rectangle "schema" {
    note "Autogenerated by Diesel" as N6
    struct "users" as schema_users
    struct "sessions" as schema_sessions
    struct "bucketlist_items" as schema_bucketlist_items
    struct "destinations" as schema_destinations
  }
}

rectangle "dto" {
  note "All structs implement serde Serialize and Deserialize" as N7
  
  struct BucketlistItemWithDestinationDTO {
    bucketlist_item: BucketlistItem
    destination: Destination
  }

  "BucketlistItem" ---d- "BucketlistItemWithDestinationDTO"
  "Destination" ---d- "BucketlistItemWithDestinationDTO"
  
  struct BucketlistItemWithPrivateListDTO {
    name: String
    latitude: f64
    longitude: f64
    start_date: NaiveDateTime
    end_date: NaiveDateTime
  }

  "NaiveDateTime" ----- "BucketlistItemWithPrivateListDTO"

  struct GetUserDTO {
    id: u64,
    role: String
    status: String
    email: String
  }

  interface "From<User>"

  "From<User>" <|-- "GetUserDTO"

  struct LoginForm {
    email: String
    password: String
  }

  struct LoginTokenClaims {
    user_id: u64
    session_id: u64
    role: String
    iat: DateTime<Utc>
    exp: DateTime<Utc>
  }

  "DateTime<Utc>" ----- "LoginTokenClaims"

  struct UserChangePasswordDTO {
    old_password: String
    new_password: String
  }
}

rectangle guard {
  metaclass "admin" {
    admin_guard(ctx: &actix_web::guard::GuardContext): bool
  }
  metaclass "employee" {
    employee_guard(ctx: &actix_web::guard::GuardContext): bool
  }

  "User" --d- "admin"
  "RoleEnum" --d- "admin"
  "User" --d- "employee"
  "RoleEnum" --d- "employee"
}

rectangle middleware {
  metaclass "auth_middleware" {
    auth_middleware(req: actix_web::dev::ServiceRequest, credentials: actix_web_httpauth::extractors::bearer::BearerAuth): Result<ServieRequest, (actix_web::error::Error, ServiceRequest)>
  }
}
@enduml
